ruby '2.5.5'
source 'https://rubygems.org'

gem 'gauge-ruby',         '0.5.0'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3'
gem 'test-unit',          '~> 3.3', '>= 3.3.3'
gem 'faker',              '1.6.6'
gem 'cpf_faker',          '1.3.0'
gem 'httparty',           '~> 0.21'
gem 'httmultiparty',      '~> 0.3'
gem 'factory_bot',        '~> 4.8.2'
gem 'pry',                '0.11.0'
gem 'rake',               '~> 12.3'